#%RAML 1.0 Trait
headers:
  client_id:
    description: Client's key
    required: true
    type: string
    displayName: Key
  client_secret:
    description: Client's secret key
    required: true
    type: string
    displayName: Secret Key